import { useId } from 'react'

/**
 * The PTUI emblem - the same mark the guild portal draws
 * (nms.bestemu.com/guilds, generated by routes/characters._build_ptui_emblem)
 * and the same one the in-game all-in-one chat bar renders.
 *
 * Geometry is ported verbatim from that SVG rather than re-derived, so the app
 * mark and the site mark are the same mark: a graduated dial, two counter
 * turning rings, and the triad - sky at the apex, ember lower right, jade
 * lower left - which are also the trio slot colours used everywhere else here.
 *
 * Motion mirrors NMSTheme::DrawEmblem (see the guild portal's stylesheet):
 * 0.55 rad/s out (11.4s), 0.38 rad/s back (16.5s), a 4.5s halo breath, and
 * nodes on a 3.0s pulse offset by a third each so the trio shimmers rather
 * than blinking in unison.
 */

/** Twelve graduations; every third is major - longer, brighter, wider. */
const TICKS = [
  { x1: 149.6, y1: 100.0, x2: 161.4, y2: 100.0, major: true },
  { x1: 147.3, y1: 127.3, x2: 153.2, y2: 130.7, major: false },
  { x1: 127.3, y1: 147.3, x2: 130.7, y2: 153.2, major: false },
  { x1: 100.0, y1: 149.6, x2: 100.0, y2: 161.4, major: true },
  { x1: 72.7, y1: 147.3, x2: 69.3, y2: 153.2, major: false },
  { x1: 52.7, y1: 127.3, x2: 46.8, y2: 130.7, major: false },
  { x1: 50.4, y1: 100.0, x2: 38.6, y2: 100.0, major: true },
  { x1: 52.7, y1: 72.7, x2: 46.8, y2: 69.3, major: false },
  { x1: 72.7, y1: 52.7, x2: 69.3, y2: 46.8, major: false },
  { x1: 100.0, y1: 50.4, x2: 100.0, y2: 38.6, major: true },
  { x1: 127.3, y1: 52.7, x2: 130.7, y2: 46.8, major: false },
  { x1: 147.3, y1: 72.7, x2: 153.2, y2: 69.3, major: false }
]

/** Triangle apex up: sky top, ember lower-right, jade lower-left. */
const NODES = [
  { cls: 'pt-n1', x: 100.0, y: 62.8, color: '#2892d8' },
  { cls: 'pt-n2', x: 132.2, y: 118.6, color: '#f0621f' },
  { cls: 'pt-n3', x: 67.8, y: 118.6, color: '#1fa878' }
]

const TRIANGLE = NODES.map((n) => `${n.x},${n.y}`).join(' ')

export function Crest({ size = 44, spin = true }: { size?: number; spin?: boolean }): JSX.Element {
  // Gradient ids must be unique per instance: the title bar and the hero both
  // render a crest, and duplicate ids would make one steal the other's fills.
  const uid = useId().replace(/:/g, '')
  const id = (n: string): string => `${n}-${uid}`

  return (
    <svg
      className={spin ? 'ptui-emblem' : 'ptui-emblem still'}
      width={size}
      height={size}
      viewBox="0 0 200 200"
      fill="none"
      role="img"
      aria-label="Project Triune"
    >
      <defs>
        <radialGradient id={id('pthalo')}>
          <stop offset=".52" stopColor="#3474be" stopOpacity="0" />
          <stop offset=".72" stopColor="#8fd0ff" stopOpacity=".22" />
          <stop offset="1" stopColor="#8fd0ff" stopOpacity="0" />
        </radialGradient>
        {NODES.map((n, i) => (
          <radialGradient key={n.cls} id={id(`ptn${i + 1}`)}>
            <stop offset="0" stopColor={n.color} stopOpacity=".55" />
            <stop offset=".38" stopColor={n.color} stopOpacity=".26" />
            <stop offset="1" stopColor={n.color} stopOpacity="0" />
          </radialGradient>
        ))}
      </defs>

      {/* Halo, breathing on its own 4.5s cycle */}
      <circle className="pt-h3" cx="100" cy="100" r="96.1" fill={`url(#${id('pthalo')})`} />

      {/* Dial face */}
      <circle cx="100" cy="100" r="61.4" fill="#080f1c" fillOpacity=".82" />

      {/* Graduations - the outer ring, turning clockwise */}
      <g className="pt-out" stroke="#8fd0ff" strokeLinecap="round">
        {TICKS.map((t, i) => (
          <line
            key={i}
            x1={t.x1}
            y1={t.y1}
            x2={t.x2}
            y2={t.y2}
            strokeOpacity={t.major ? '.86' : '.43'}
            strokeWidth={t.major ? 2.0 : 1.3}
          />
        ))}
      </g>

      {/* The two fixed rings the graduations read against */}
      <circle cx="100" cy="100" r="61.4" fill="none" stroke="#8fd0ff" strokeOpacity=".82" strokeWidth="1.7" />
      <circle cx="100" cy="100" r="45.9" fill="none" stroke="#8fd0ff" strokeOpacity=".27" strokeWidth="1.2" />

      {/* The triad, turning back the other way */}
      <g className="pt-in">
        <polygon points={TRIANGLE} fill="#5a82c8" fillOpacity=".10" />
        <polygon
          points={TRIANGLE}
          fill="none"
          stroke="#8fa5eb"
          strokeOpacity=".75"
          strokeWidth="1.5"
          strokeLinejoin="round"
        />
        {NODES.map((n, i) => (
          <g className={`pt-node ${n.cls}`} key={n.cls}>
            <circle className="pt-g1" cx={n.x} cy={n.y} r="20" fill={`url(#${id(`ptn${i + 1}`)})`} />
            <circle cx={n.x} cy={n.y} r="5.9" fill={n.color} />
            {/* Offset highlight - keeps the node reading as a light source */}
            <circle cx={n.x - 1.6} cy={n.y - 1.6} r="2.1" fill="#ffffff" fillOpacity=".8" />
          </g>
        ))}
      </g>
    </svg>
  )
}
